### ISSUE TITLE
Bug when used with Linear XP

### ISSUE THREAD

**Issue by ultimatejacob27** [B1n-ry/Youre-in-grave-danger#160]
When used with Linear XP, the amount of xp preserved is much lower than the percentage set to dropPercentage.

**Comment by B1n-ry** [comment]
I assume by "much lower" you mean that XP is floored to whole levels. I've managed to find and fix the issue in my dev environment, and will be fixed publicly in the next update.
Also, when reporting a practical example would be cool to know of. I still really appreciate you reporting the issue! A little information is always better than none at all!

**Comment by B1n-ry** [comment]
If this was indeed the issue, it's fixed in 2.0.0-beta.12

**Comment by mustbetommy** [comment]
I'm still encountering this issue. I'm using version 2.0.10 and XP settings are PERCENTAGE and dropPercentage is set to 100. However, if I have 8 levels, only 3 return.

**Comment by B1n-ry** [comment]
Are these configs on the server you're playing on? I could not reproduce this, so I just want to make sure that you're not just setting the configs on your client, in a server you're playing on
