### ISSUE TITLE
Server crash when dying with travelers backpack

### ISSUE THREAD

**Issue by Hippopipo** [B1n-ry/Youre-in-grave-danger#199]
Log: https://mclo.gs/x0L59uz
Happened after traveler's backpack update. I saw the other issue about this, but wasn't sure if this was the same thing, so i made this issue.

**Comment by Hippopipo** [comment]
Workaround for anybody who has this issue: Set "enableTravelersBackpackCompat" to false

**Comment by B1n-ry** [comment]
Should be fixed in newest update (2.4.12 for fabric 1.21)

**Comment by Avamander** [comment]
@B1n-ry Unfortunately I'm still encountering the crash on Minecraft 1.21.1 + Fabric, using Traveler's Backpack 10.1.6 and YIGD 2.4.12. Do I need to use some other version? 

<details>

```
[18:33:14] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoClassDefFoundError: com/tiviacz/travelersbackpack/capability/AttachmentUtils
	at knot/com.b1n_ry.yigd.compat.TravelersBackpackCompat$TBCompatComponent.getInventory(TravelersBackpackCompat.java:71) ~[youre-in-grave-danger-fabric-2.4.12.jar:?]
	at knot/com.b1n_ry.yigd.compat.TravelersBackpackCompat$TBCompatComponent.getInventory(TravelersBackpackCompat.java:58) ~[youre-in-grave-danger-fabric-2.4.12.jar:?]
	at knot/com.b1n_ry.yigd.compat.CompatComponent.<init>(CompatComponent.java:22) ~[youre-in-grave-danger-fabric-2.4.12.jar:?]
	at knot/com.b1n_ry.yigd.compat.TravelersBackpackCompat$TBCompatComponent.<init>(TravelersBackpackCompat.java:61) ~[youre-in-grave-danger-fabric-2.4.12.jar:?]
	at knot/com.b1n_ry.yigd.compat.TravelersBackpackCompat.getNewComponent(TravelersBackpackCompat.java:55) ~[youre-in-grave-danger-fabric-2.4.12.jar:?]
	at knot/com.b1n_ry.yigd.components.InventoryComponent.getModInventoryItems(InventoryComponent.java:127) ~[youre-in-grave-danger-fabric-2.4.12.jar:?]
	at knot/com.b1n_ry.yigd.components.InventoryComponent.<init>(InventoryComponent.java:53) ~[youre-in-grave-danger-fabric-2.4.12.jar:?]
	at knot/com.b1n_ry.yigd.DeathHandler.onPlayerDeath(DeathHandler.java:36) ~[youre-in-grave-danger-fabric-2.4.12.jar:?]
	at knot/net.minecraft.class_1309.handler$fnh000$yigd$drop(class_1309.java:4800) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1309.method_16080(class_1309.java) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_3222.method_6078(class_3222.java:725) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1309.method_5643(class_1309.java:1252) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1657.method_5643(class_1657.java:977) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_3222.method_5643(class_3222.java:811) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1309.method_5747(class_1309.java:1630) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1657.method_5747(class_1657.java:1675) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2248.method_9554(class_2248.java:465) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1297.method_5623(class_1297.java:1363) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1309.method_5623(class_1309.java:374) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_3222.method_14207(class_3222.java:1118) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_3244.method_12063(class_3244.java:1000) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2828.method_12272(class_2828.java:142) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2828$class_2830.method_11054(class_2828.java:18) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2600.method_11072(class_2600.java:27) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_3738.run(class_3738.java:18) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_18859(class_1255.java:162) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:864) ~[client-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:173) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_16075(class_1255.java:136) ~[client-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:846) ~[client-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:840) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_18857(class_1255.java:145) ~[client-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_18857(MinecraftServer.java:810) ~[client-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:815) ~[client-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:702) ~[client-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281) ~[client-intermediary.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1575) [?:?]
Caused by: java.lang.ClassNotFoundException: com.tiviacz.travelersbackpack.capability.AttachmentUtils
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:528) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.16.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.10.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:528) ~[?:?]
	... 38 more
[18:33:14] [Render thread/INFO]: [CHAT] Avamander fell from a high place
[18:33:14] [Server thread/ERROR]: This crash report has been saved to: instances\1.21.1\.minecraft\crash-reports\crash-2025-01-09_18.33.14-server.txt
---- Minecraft Crash Report ----
// Why is it breaking :(

Time: 2025-01-09 18:33:14
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: com/tiviacz/travelersbackpack/capability/AttachmentUtils
	at knot//com.b1n_ry.yigd.compat.TravelersBackpackCompat$TBCompatComponent.getInventory(TravelersBackpackCompat.java:71)
	at knot//com.b1n_ry.yigd.compat.TravelersBackpackCompat$TBCompatComponent.getInventory(TravelersBackpackCompat.java:58)
	at knot//com.b1n_ry.yigd.compat.CompatComponent.<init>(CompatComponent.java:22)
	at knot//com.b1n_ry.yigd.compat.TravelersBackpackCompat$TBCompatComponent.<init>(TravelersBackpackCompat.java:61)
	at knot//com.b1n_ry.yigd.compat.TravelersBackpackCompat.getNewComponent(TravelersBackpackCompat.java:55)
	at knot//com.b1n_ry.yigd.components.InventoryComponent.getModInventoryItems(InventoryComponent.java:127)
	at knot//com.b1n_ry.yigd.components.InventoryComponent.<init>(InventoryComponent.java:53)
	at knot//com.b1n_ry.yigd.DeathHandler.onPlayerDeath(DeathHandler.java:36)
	at knot//net.minecraft.class_1309.handler$fnh000$yigd$drop(class_1309.java:4800)
	at knot//net.minecraft.class_1309.method_16080(class_1309.java)
	at knot//net.minecraft.class_3222.method_6078(class_3222.java:725)
	at knot//net.minecraft.class_1309.method_5643(class_1309.java:1252)
	at knot//net.minecraft.class_1657.method_5643(class_1657.java:977)
	at knot//net.minecraft.class_3222.method_5643(class_3222.java:811)
	at knot//net.minecraft.class_1309.method_5747(class_1309.java:1630)
	at knot//net.minecraft.class_1657.method_5747(class_1657.java:1675)
	at knot//net.minecraft.class_2248.method_9554(class_2248.java:465)
	at knot//net.minecraft.class_1297.method_5623(class_1297.java:1363)
	at knot//net.minecraft.class_1309.method_5623(class_1309.java:374)
	at knot//net.minecraft.class_3222.method_14207(class_3222.java:1118)
	at knot//net.minecraft.class_3244.method_12063(class_3244.java:1000)
	at knot//net.minecraft.class_2828.method_12272(class_2828.java:142)
	at knot//net.minecraft.class_2828$class_2830.method_11054(class_2828.java:18)
	at knot//net.minecraft.class_2600.method_11072(class_2600.java:27)
	at knot//net.minecraft.class_3738.run(class_3738.java:18)
	at knot//net.minecraft.class_1255.method_18859(class_1255.java:162)
	at knot//net.minecraft.class_4093.method_18859(class_4093.java:23)
	at knot//net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:864)
	at knot//net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:173)
	at knot//net.minecraft.class_1255.method_16075(class_1255.java:136)
	at knot//net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:846)
	at knot//net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:840)
	at knot//net.minecraft.class_1255.method_18857(class_1255.java:145)
	at knot//net.minecraft.server.MinecraftServer.method_18857(MinecraftServer.java:810)
	at knot//net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:815)
	at knot//net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:702)
	at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
	at java.base/java.lang.Thread.run(Thread.java:1575)
Caused by: java.lang.ClassNotFoundException: com.tiviacz.travelersbackpack.capability.AttachmentUtils
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:528)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:528)
	... 38 more
```
</details>

**Comment by B1n-ry** [comment]
Umm so I did manage to reproduce the issue, but I have no idea why it occurs. I'll look into it over the next couple of days

**Comment by lmc-jarred** [comment]
I am also encountering this crash when I die regardless of what I have in my inventory (backpack, no backpack, or nothing at all), but only when enableTravelersBackpackCompat is set to true. If I die with it set to false, then I do not crash, but the backpack pops out like an item normally would instead of going into the grave (which I'm assuming is expected behavior when that setting is false). If the backpack is in one of my inventory slots when I die instead of "on my back" while the setting is false, then there is no issue.

I am playing on Minecraft 1.21.1 with Fabric Loader 0.114.0, You're in Grave Danger 2.4.12, and Traveler's Backpack [Fabric] 10.1.3.

<details>
<summary>Error log with error code -1</summary>
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2025-01-09 21:59:30
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: com/tiviacz/travelersbackpack/capability/AttachmentUtils
	at knot//com.b1n_ry.yigd.compat.TravelersBackpackCompat$TBCompatComponent.getInventory(TravelersBackpackCompat.java:71)
	at knot//com.b1n_ry.yigd.compat.TravelersBackpackCompat$TBCompatComponent.getInventory(TravelersBackpackCompat.java:58)
	at knot//com.b1n_ry.yigd.compat.CompatComponent.<init>(CompatComponent.java:22)
	at knot//com.b1n_ry.yigd.compat.TravelersBackpackCompat$TBCompatComponent.<init>(TravelersBackpackCompat.java:61)
	at knot//com.b1n_ry.yigd.compat.TravelersBackpackCompat.getNewComponent(TravelersBackpackCompat.java:55)
	at knot//com.b1n_ry.yigd.components.InventoryComponent.getModInventoryItems(InventoryComponent.java:127)
	at knot//com.b1n_ry.yigd.components.InventoryComponent.<init>(InventoryComponent.java:53)
	at knot//com.b1n_ry.yigd.DeathHandler.onPlayerDeath(DeathHandler.java:36)
	at knot//net.minecraft.class_1309.handler$ceh000$yigd$drop(class_1309.java:3800)
	at knot//net.minecraft.class_1309.method_16080(class_1309.java)
	at knot//net.minecraft.class_3222.method_6078(class_3222.java:725)
	at knot//net.minecraft.class_1309.method_5643(class_1309.java:1252)
	at knot//net.minecraft.class_1657.method_5643(class_1657.java:977)
	at knot//net.minecraft.class_3222.method_5643(class_3222.java:811)
	at knot//net.minecraft.class_1309.method_5747(class_1309.java:1630)
	at knot//net.minecraft.class_1657.method_5747(class_1657.java:1675)
	at knot//net.minecraft.class_2248.method_9554(class_2248.java:465)
	at knot//net.minecraft.class_1297.method_5623(class_1297.java:1363)
	at knot//net.minecraft.class_1309.method_5623(class_1309.java:374)
	at knot//net.minecraft.class_3222.method_14207(class_3222.java:1118)
	at knot//net.minecraft.class_3244.method_12063(class_3244.java:1000)
	at knot//net.minecraft.class_2828.method_12272(class_2828.java:142)
	at knot//net.minecraft.class_2828$class_2829.method_11054(class_2828.java:50)
	at knot//net.minecraft.class_2600.method_11072(class_2600.java:27)
	at knot//net.minecraft.class_3738.run(class_3738.java:18)
	at knot//net.minecraft.class_1255.method_18859(class_1255.java:162)
	at knot//net.minecraft.class_4093.method_18859(class_4093.java:23)
	at knot//net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:864)
	at knot//net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:173)
	at knot//net.minecraft.class_1255.method_16075(class_1255.java:136)
	at knot//net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:846)
	at knot//net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:840)
	at knot//net.minecraft.class_1255.method_18857(class_1255.java:145)
	at knot//net.minecraft.server.MinecraftServer.method_18857(MinecraftServer.java:810)
	at knot//net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:815)
	at knot//net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:702)
	at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.ClassNotFoundException: com.tiviacz.travelersbackpack.capability.AttachmentUtils
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 38 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Cobblemon --
Details:
	Version: 1.6.0
	Is Snapshot: false
	Git Commit: 2e3302b (https://gitlab.com/cable-mc/cobblemon/-/commit/2e3302bdec487bf11cace370cffd38f1837ae96b)
	Branch: HEAD

-- System Details --
Details:
	Minecraft Version: 1.21.1
	Minecraft Version ID: 1.21.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 192935936 bytes (183 MiB) / 2799697920 bytes (2670 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 5
	Microarchitecture: Comet Lake
	Frequency (GHz): 3.79
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce GTX 980 Ti
	Graphics card #0 vendor: NVIDIA
	Graphics card #0 VRAM (MiB): 6144.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 32.0.15.6094
	Memory slot #0 capacity (MiB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MiB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MiB): 118943.74
	Virtual memory used (MiB): 102287.09
	Swap memory total (MiB): 86322.14
	Swap memory used (MiB): 21848.74
	Space in storage for jna.tmpdir (MiB): available: 72007.06, total: 476313.06
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 72007.06, total: 476313.06
	Space in storage for io.netty.native.workdir (MiB): available: 72007.06, total: 476313.06
	Space in storage for java.io.tmpdir (MiB): available: 72007.06, total: 476313.06
	Space in storage for workdir (MiB): available: 72007.06, total: 476313.06
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	Fabric Mods: 
		cardinal-components: Cardinal Components API 6.1.1
			cardinal-components-base: Cardinal Components API (base) 6.1.1
			cardinal-components-block: Cardinal Components API (blocks) 6.1.1
			cardinal-components-chunk: Cardinal Components API (chunks) 6.1.1
			cardinal-components-entity: Cardinal Components API (entities) 6.1.1
			cardinal-components-item: Cardinal Components API (items) 6.1.1
			cardinal-components-level: Cardinal Components API (world saves) 6.1.1
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 6.1.1
			cardinal-components-world: Cardinal Components API (worlds) 6.1.1
		cloth-config: Cloth Config v15 15.0.140
			cloth-basic-math: cloth-basic-math 0.6.1
		cobblemon: Cobblemon 1.6.0+1.21.1
			fabric-language-kotlin: Fabric Language Kotlin 1.11.0+kotlin.2.0.0
				org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.0
				org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.0
				org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.0
				org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.0
				org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.24.0
				org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.1
				org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.1
				org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.0
				org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.3
				org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.3
				org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.3
		elementa: Elementa 670
		entityculling: EntityCulling 1.7.2
		essential: Essential 1.3.5.5
		essential-container: essential-container 1.0.0
			essential-loader: essential-loader 1.2.3
		fabric-api: Fabric API 0.114.0+1.21.1
			fabric-api-base: Fabric API Base 0.4.42+6573ed8c19
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.70+b559734419
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.31+d527f9fd19
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a719
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8c19
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a719
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8c19
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366f19
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd919
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b319
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.18+b559734419
			fabric-convention-tags-v1: Fabric Convention Tags 2.1.2+7f945d5b19
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.9.2+e60e56d419
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a719
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.4.0+da19b51a19
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.25+16c4ae2519
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b9919
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.7.0+2122d82819
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.13+ba9dae0619
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd919
			fabric-item-api-v1: Fabric Item API (v1) 11.1.1+d5debaed19
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.6+6823f7cd19
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a719
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b319
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.5.0+01d9a51c19
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.15+3f89f5a519
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.3+3f89f5a519
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8c19
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6b19
			fabric-networking-api-v1: Fabric Networking API (v1) 4.3.0+c7469b2119
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.2.1+40875a9319
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8c19
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.14+248df81c19
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.2.0+34f5d91419
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.4.0+c705a49c19
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.7.0+c705a49c19
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.68+df3654b319
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2e19
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+1daea21519
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.71+df3654b319
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.5+df16efd019
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.3.0+8dc279b119
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.3.1+5b5275af19
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.25+8b68f1c719
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.88+b559734419
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8c19
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.4.2+c24bd99419
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.2.0+45b9699719
		fabricloader: Fabric Loader 0.16.9
			mixinextras: MixinExtras 0.4.1
		ferritecore: FerriteCore 7.0.2-hotfix
		immediatelyfast: ImmediatelyFast 1.3.3+1.21.1
			net_lenni0451_reflect: Reflect 1.3.4
		jade: Jade 15.9.2+fabric
		java: OpenJDK 64-Bit Server VM 21
		jei: Just Enough Items 19.8.4.113
		krypton: Krypton 0.2.8
			com_velocitypowered_velocity-native: velocity-native 3.3.0-SNAPSHOT
		lambdynlights: LambDynamicLights 3.1.4+1.21.1
			pride: Pride Lib 1.2.1+1.21
			spruceui: SpruceUI 5.1.0+1.21
		lithium: Lithium 0.14.3-snapshot+mc1.21.1-build.92
		minecraft: Minecraft 1.21.1
		modmenu: Mod Menu 11.0.3
		org_jetbrains_annotations: annotations 23.0.0
		placeholder-api: Placeholder API 2.4.1+1.21
		reeses-sodium-options: Reese's Sodium Options 1.8.0+mc1.21.3
		sodium: Sodium 0.6.5+mc1.21.1
		travelersbackpack: Traveler's Backpack 10.1.3
		universalcraft: UniversalCraft 365
		vigilance: Vigilance 306
		xaerominimap: Xaero's Minimap 24.7.1
		xaeroworldmap: Xaero's World Map 1.39.2
		yigd: You're in Grave Danger 2.4.12
			fabric-permissions-api-v0: fabric-permissions-api 0.3.1
			libgui: LibGui 11.1.0+1.21
				jankson: Jankson 8.0.0+j1.2.3
					blue_endless_jankson: jankson 1.2.3
				libninepatch: LibNinePatch 1.2.0
	Server Running: true
	Player Count: 1 / 8; [class_3222['Mister_Miner369'/8516, l='ServerLevel[Modpack Test 2025-01-08_01]', x=-1.95, y=63.00, z=9.43]]
	Active Data Packs: vanilla, fabric, cobblemon, fabric-convention-tags-v2, travelersbackpack, yigd
	Available Data Packs: bundle, cobblemon, fabric, fabric-convention-tags-v2, trade_rebalance, travelersbackpack, vanilla, yigd
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	World Seed: 424090864491570691
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: fabric-loader-0.16.9-1.21.1
</details>

**Comment by B1n-ry** [comment]
Apparently I mistakenly fixed compat with 10.1.6 *neoforge* instead of fabric. The issue has been rectified and a new version has been released, containing the fix.

**Comment by lmc-jarred** [comment]
Sorry to say, I'm still crashing on death after updating YIGD to 2.4.13 with Traveler's Backpack, but it is a different error type: NoSuchMethodError instead of NoClassDefFoundError. Let me know if I can provide any other info to help diagnose/rectify this.

<details>
<summary>Error log with exit code -1</summary>
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2025-01-10 09:54:13
Description: Exception in server tick loop

java.lang.NoSuchMethodError: 'java.util.Optional com.tiviacz.travelersbackpack.component.ComponentUtils.getComponent(net.minecraft.class_1657)'
	at knot//com.b1n_ry.yigd.compat.TravelersBackpackCompat.clear(TravelersBackpackCompat.java:37)
	at knot//com.b1n_ry.yigd.components.InventoryComponent.clearPlayer(InventoryComponent.java:722)
	at knot//com.b1n_ry.yigd.DeathHandler.onPlayerDeath(DeathHandler.java:39)
	at knot//net.minecraft.class_1309.handler$cga000$yigd$drop(class_1309.java:3800)
	at knot//net.minecraft.class_1309.method_16080(class_1309.java)
	at knot//net.minecraft.class_3222.method_6078(class_3222.java:725)
	at knot//net.minecraft.class_1309.method_5643(class_1309.java:1252)
	at knot//net.minecraft.class_1657.method_5643(class_1657.java:977)
	at knot//net.minecraft.class_3222.method_5643(class_3222.java:811)
	at knot//net.minecraft.class_1309.method_5768(class_1309.java:300)
	at knot//net.minecraft.class_3075.method_13430(class_3075.java:32)
	at knot//net.minecraft.class_3075.method_22832(class_3075.java:22)
	at knot//com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
	at knot//net.minecraft.class_8865.method_54416(class_8865.java:29)
	at knot//net.minecraft.class_8865.execute(class_8865.java:13)
	at knot//net.minecraft.class_8856.method_54405(class_8856.java:8)
	at knot//net.minecraft.class_8847.method_54388(class_8847.java:8)
	at knot//net.minecraft.class_8854.method_54390(class_8854.java:107)
	at knot//net.minecraft.class_2170.method_54313(class_2170.java:379)
	at knot//net.minecraft.class_2170.method_9249(class_2170.java:309)
	at knot//net.minecraft.class_3244.method_58590(class_3244.java:1319)
	at knot//net.minecraft.class_3244.method_44356(class_3244.java:1307)
	at knot//net.minecraft.class_3738.run(class_3738.java:18)
	at knot//net.minecraft.class_1255.method_18859(class_1255.java:162)
	at knot//net.minecraft.class_4093.method_18859(class_4093.java:23)
	at knot//net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:864)
	at knot//net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:173)
	at knot//net.minecraft.class_1255.method_16075(class_1255.java:136)
	at knot//net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:846)
	at knot//net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:840)
	at knot//net.minecraft.class_1255.method_5383(class_1255.java:121)
	at knot//net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:814)
	at knot//net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:702)
	at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
	at java.base/java.lang.Thread.run(Thread.java:1583)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Cobblemon --
Details:
	Version: 1.6.0
	Is Snapshot: false
	Git Commit: 2e3302b (https://gitlab.com/cable-mc/cobblemon/-/commit/2e3302bdec487bf11cace370cffd38f1837ae96b)
	Branch: HEAD

-- System Details --
Details:
	Minecraft Version: 1.21.1
	Minecraft Version ID: 1.21.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 695911456 bytes (663 MiB) / 2170552320 bytes (2070 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 5
	Microarchitecture: Comet Lake
	Frequency (GHz): 3.79
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce GTX 980 Ti
	Graphics card #0 vendor: NVIDIA
	Graphics card #0 VRAM (MiB): 6144.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 32.0.15.6094
	Memory slot #0 capacity (MiB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MiB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MiB): 118943.74
	Virtual memory used (MiB): 101567.21
	Swap memory total (MiB): 86322.14
	Swap memory used (MiB): 20681.29
	Space in storage for jna.tmpdir (MiB): available: 71691.30, total: 476313.06
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 71691.30, total: 476313.06
	Space in storage for io.netty.native.workdir (MiB): available: 71691.30, total: 476313.06
	Space in storage for java.io.tmpdir (MiB): available: 71691.30, total: 476313.06
	Space in storage for workdir (MiB): available: 71691.30, total: 476313.06
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	Fabric Mods: 
		cardinal-components: Cardinal Components API 6.1.1
			cardinal-components-base: Cardinal Components API (base) 6.1.1
			cardinal-components-block: Cardinal Components API (blocks) 6.1.1
			cardinal-components-chunk: Cardinal Components API (chunks) 6.1.1
			cardinal-components-entity: Cardinal Components API (entities) 6.1.1
			cardinal-components-item: Cardinal Components API (items) 6.1.1
			cardinal-components-level: Cardinal Components API (world saves) 6.1.1
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 6.1.1
			cardinal-components-world: Cardinal Components API (worlds) 6.1.1
		cloth-config: Cloth Config v15 15.0.140
			cloth-basic-math: cloth-basic-math 0.6.1
		cobblemon: Cobblemon 1.6.0+1.21.1
			fabric-language-kotlin: Fabric Language Kotlin 1.11.0+kotlin.2.0.0
				org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.0
				org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.0
				org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.0
				org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.0
				org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.24.0
				org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.1
				org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.1
				org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.0
				org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.3
				org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.3
				org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.3
		elementa: Elementa 670
		entityculling: EntityCulling 1.7.2
		essential: Essential 1.3.5.5
		essential-container: essential-container 1.0.0
			essential-loader: essential-loader 1.2.3
		fabric-api: Fabric API 0.114.0+1.21.1
			fabric-api-base: Fabric API Base 0.4.42+6573ed8c19
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.70+b559734419
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.31+d527f9fd19
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a719
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8c19
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a719
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8c19
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366f19
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd919
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b319
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.18+b559734419
			fabric-convention-tags-v1: Fabric Convention Tags 2.1.2+7f945d5b19
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.9.2+e60e56d419
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a719
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.4.0+da19b51a19
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.25+16c4ae2519
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b9919
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.7.0+2122d82819
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.13+ba9dae0619
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd919
			fabric-item-api-v1: Fabric Item API (v1) 11.1.1+d5debaed19
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.6+6823f7cd19
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a719
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b319
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.5.0+01d9a51c19
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.15+3f89f5a519
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.3+3f89f5a519
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8c19
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6b19
			fabric-networking-api-v1: Fabric Networking API (v1) 4.3.0+c7469b2119
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.2.1+40875a9319
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8c19
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.14+248df81c19
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.2.0+34f5d91419
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.4.0+c705a49c19
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.7.0+c705a49c19
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.68+df3654b319
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2e19
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+1daea21519
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.71+df3654b319
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.5+df16efd019
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.3.0+8dc279b119
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.3.1+5b5275af19
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.25+8b68f1c719
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.88+b559734419
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8c19
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.4.2+c24bd99419
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.2.0+45b9699719
		fabricloader: Fabric Loader 0.16.9
			mixinextras: MixinExtras 0.4.1
		ferritecore: FerriteCore 7.0.2-hotfix
		framework: Framework 0.9.4
			com_electronwill_night-config_core: core 3.7.1
			com_electronwill_night-config_toml: toml 3.7.1
			org_javassist_javassist: javassist 3.29.2-GA
			org_reflections_reflections: reflections 0.10.2
		immediatelyfast: ImmediatelyFast 1.3.3+1.21.1
			net_lenni0451_reflect: Reflect 1.3.4
		jade: Jade 15.9.2+fabric
		java: OpenJDK 64-Bit Server VM 21
		jei: Just Enough Items 19.8.4.113
		krypton: Krypton 0.2.8
			com_velocitypowered_velocity-native: velocity-native 3.3.0-SNAPSHOT
		lambdynlights: LambDynamicLights 3.1.4+1.21.1
			pride: Pride Lib 1.2.1+1.21
			spruceui: SpruceUI 5.1.0+1.21
		lithium: Lithium 0.14.3-snapshot+mc1.21.1-build.92
		minecraft: Minecraft 1.21.1
		modmenu: Mod Menu 11.0.3
		org_jetbrains_annotations: annotations 23.0.0
		placeholder-api: Placeholder API 2.4.1+1.21
		reeses-sodium-options: Reese's Sodium Options 1.8.0+mc1.21.3
		refurbished_furniture: MrCrayfish's Furniture Mod: Refurbished 1.0.8
		sodium: Sodium 0.6.5+mc1.21.1
		travelersbackpack: Traveler's Backpack 10.1.3
		universalcraft: UniversalCraft 365
		vigilance: Vigilance 306
		xaerominimap: Xaero's Minimap 24.7.1
		xaeroworldmap: Xaero's World Map 1.39.2
		yigd: You're in Grave Danger 2.4.13
			fabric-permissions-api-v0: fabric-permissions-api 0.3.1
			libgui: LibGui 11.1.0+1.21
				jankson: Jankson 8.0.0+j1.2.3
					blue_endless_jankson: jankson 1.2.3
				libninepatch: LibNinePatch 1.2.0
	Server Running: true
	Player Count: 1 / 8; [class_3222['Mister_Miner369'/72, l='ServerLevel[Modpack Test 2025-01-08_01]', x=-5.50, y=63.00, z=-2.50]]
	Active Data Packs: vanilla, fabric, cobblemon, fabric-convention-tags-v2, refurbished_furniture (incompatible), travelersbackpack, yigd
	Available Data Packs: bundle, cobblemon, fabric, fabric-convention-tags-v2, refurbished_furniture (incompatible), trade_rebalance, travelersbackpack, vanilla, yigd
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	World Seed: 424090864491570691
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: fabric-loader-0.16.9-1.21.1
</details>

**Comment by B1n-ry** [comment]
Update travelers backpack to 10.1.6

**Comment by lmc-jarred** [comment]
That did it, thank you!

**Comment by Avamander** [comment]
@lmc-jarred I do not seem to be having any problems after updating everything to latest versions.
